"""
Problem Cache for Planner Training

Caches VRP problems generated by diffusion models to avoid repeated sampling.
This significantly speeds up training since diffusion sampling is slow (~540ms/sample).

Key features:
1. Per-version problem storage (each generator version has its own cache)
2. Configurable cache size per version
3. Support for cache reuse ratio (mix of cached and fresh problems)
4. Disk persistence for cross-run caching
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any
import os
import time
import json
import random
import torch
import numpy as np
from pathlib import Path


@dataclass
class CachedProblem:
    """A single cached VRP problem."""
    depot_xy: torch.Tensor      # (1, 2) - normalized [0,1]
    node_xy: torch.Tensor       # (N, 2) - normalized [0,1]
    node_demand: torch.Tensor   # (N,) - normalized by DEMAND_NORM
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to serializable dict."""
        return {
            "depot_xy": self.depot_xy.cpu().numpy().tolist(),
            "node_xy": self.node_xy.cpu().numpy().tolist(),
            "node_demand": self.node_demand.cpu().numpy().tolist(),
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CachedProblem":
        """Create from dict."""
        return cls(
            depot_xy=torch.tensor(data["depot_xy"], dtype=torch.float32),
            node_xy=torch.tensor(data["node_xy"], dtype=torch.float32),
            node_demand=torch.tensor(data["node_demand"], dtype=torch.float32),
        )


class VersionProblemCache:
    """
    Cache for problems from a single generator version.
    
    Stores problems in memory with optional disk persistence.
    """
    
    def __init__(
        self,
        version_id: int,
        max_size: int = 1000,
        cache_dir: Optional[str] = None,
    ):
        """
        Args:
            version_id: Generator version ID this cache belongs to
            max_size: Maximum number of problems to cache
            cache_dir: Directory for disk persistence (None = memory only)
        """
        self.version_id = version_id
        self.max_size = max_size
        self.cache_dir = cache_dir
        
        self._problems: List[CachedProblem] = []
        self._creation_time = time.time()
        
        # Load from disk if exists
        if cache_dir:
            self._cache_path = os.path.join(cache_dir, f"problems_v{version_id}.pt")
            self._load_from_disk()
    
    def add(self, problem: CachedProblem):
        """Add a problem to cache, evicting oldest if full."""
        if len(self._problems) >= self.max_size:
            # FIFO eviction
            self._problems.pop(0)
        self._problems.append(problem)
    
    def add_batch(
        self,
        depot_xy: torch.Tensor,
        node_xy: torch.Tensor,
        node_demand: torch.Tensor,
    ):
        """
        Add a batch of problems to cache.
        
        Args:
            depot_xy: (batch_size, 1, 2)
            node_xy: (batch_size, N, 2)
            node_demand: (batch_size, N)
        """
        batch_size = depot_xy.shape[0]
        for i in range(batch_size):
            problem = CachedProblem(
                depot_xy=depot_xy[i].cpu(),        # (1, 2)
                node_xy=node_xy[i].cpu(),          # (N, 2)
                node_demand=node_demand[i].cpu(),  # (N,)
            )
            self.add(problem)
    
    def sample(self, n: int, rng: random.Random) -> List[CachedProblem]:
        """Sample n problems from cache (with replacement if needed)."""
        if not self._problems:
            return []
        
        if n <= len(self._problems):
            return rng.sample(self._problems, n)
        else:
            # Sample with replacement
            return rng.choices(self._problems, k=n)
    
    def sample_batch(
        self,
        batch_size: int,
        rng: random.Random,
        device: torch.device,
    ) -> Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor]]:
        """
        Sample a batch of problems and stack into tensors.
        
        Returns:
            (depot_xy, node_xy, node_demand) or None if cache is empty
        """
        problems = self.sample(batch_size, rng)
        if not problems:
            return None
        
        depot_xy = torch.stack([p.depot_xy for p in problems], dim=0).to(device)
        node_xy = torch.stack([p.node_xy for p in problems], dim=0).to(device)
        node_demand = torch.stack([p.node_demand for p in problems], dim=0).to(device)
        
        return depot_xy, node_xy, node_demand
    
    def size(self) -> int:
        """Return current cache size."""
        return len(self._problems)
    
    def is_full(self) -> bool:
        """Check if cache is at max capacity."""
        return len(self._problems) >= self.max_size
    
    def save_to_disk(self):
        """Persist cache to disk."""
        if not self.cache_dir:
            return
        
        os.makedirs(self.cache_dir, exist_ok=True)
        
        # Save as tensor file for efficiency
        data = {
            "version_id": self.version_id,
            "creation_time": self._creation_time,
            "problems": [p.to_dict() for p in self._problems],
        }
        torch.save(data, self._cache_path)
        print(f"[ProblemCache] Saved {len(self._problems)} problems for v{self.version_id}")
    
    def _load_from_disk(self):
        """Load cache from disk if exists."""
        if not os.path.exists(self._cache_path):
            return
        
        try:
            data = torch.load(self._cache_path, weights_only=False)
            self._creation_time = data.get("creation_time", time.time())
            self._problems = [CachedProblem.from_dict(p) for p in data["problems"]]
            print(f"[ProblemCache] Loaded {len(self._problems)} problems for v{self.version_id}")
        except Exception as e:
            print(f"[ProblemCache] Failed to load cache for v{self.version_id}: {e}")
            self._problems = []


class ProblemCacheManager:
    """
    Manager for all version-specific problem caches.
    
    Handles:
    1. Creating/retrieving per-version caches
    2. Sampling across versions with configurable policy
    3. Mixed sampling (cached + fresh generation)
    """
    
    def __init__(
        self,
        cache_dir: str = "checkpoints/adversarial_v2/problem_cache",
        max_problems_per_version: int = 1000,
        cache_reuse_ratio: float = 0.8,
        min_cache_size_for_reuse: int = 100,
    ):
        """
        Args:
            cache_dir: Directory for disk persistence
            max_problems_per_version: Max problems to cache per generator version
            cache_reuse_ratio: Probability of using cached problem vs generating new
                              (0.0 = always generate new, 1.0 = always use cache)
            min_cache_size_for_reuse: Minimum cache size before enabling reuse
        """
        self.cache_dir = cache_dir
        self.max_problems_per_version = max_problems_per_version
        self.cache_reuse_ratio = cache_reuse_ratio
        self.min_cache_size_for_reuse = min_cache_size_for_reuse
        
        self._version_caches: Dict[int, VersionProblemCache] = {}
        
        # Load existing caches from disk
        self._load_existing_caches()
    
    def _load_existing_caches(self):
        """Load all existing caches from disk."""
        if not os.path.exists(self.cache_dir):
            return
        
        for filename in os.listdir(self.cache_dir):
            if filename.startswith("problems_v") and filename.endswith(".pt"):
                try:
                    # Extract version ID from filename
                    version_id = int(filename.replace("problems_v", "").replace(".pt", ""))
                    cache = VersionProblemCache(
                        version_id=version_id,
                        max_size=self.max_problems_per_version,
                        cache_dir=self.cache_dir,
                    )
                    if cache.size() > 0:
                        self._version_caches[version_id] = cache
                except Exception as e:
                    print(f"[ProblemCacheManager] Failed to load {filename}: {e}")
    
    def get_or_create_cache(self, version_id: int) -> VersionProblemCache:
        """Get cache for a version, creating if needed."""
        if version_id not in self._version_caches:
            self._version_caches[version_id] = VersionProblemCache(
                version_id=version_id,
                max_size=self.max_problems_per_version,
                cache_dir=self.cache_dir,
            )
        return self._version_caches[version_id]
    
    def add_problems(
        self,
        version_id: int,
        depot_xy: torch.Tensor,
        node_xy: torch.Tensor,
        node_demand: torch.Tensor,
    ):
        """Add generated problems to a version's cache."""
        cache = self.get_or_create_cache(version_id)
        cache.add_batch(depot_xy, node_xy, node_demand)
    
    def should_use_cache(self, version_id: int, rng: random.Random) -> bool:
        """
        Decide whether to use cached problem or generate new.
        
        Returns True if:
        1. Cache for this version has enough problems
        2. Random draw says to use cache (based on cache_reuse_ratio)
        """
        if version_id not in self._version_caches:
            return False
        
        cache = self._version_caches[version_id]
        if cache.size() < self.min_cache_size_for_reuse:
            return False
        
        return rng.random() < self.cache_reuse_ratio
    
    def sample_from_cache(
        self,
        version_id: int,
        batch_size: int,
        rng: random.Random,
        device: torch.device,
    ) -> Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor]]:
        """Sample a batch from a specific version's cache."""
        if version_id not in self._version_caches:
            return None
        return self._version_caches[version_id].sample_batch(batch_size, rng, device)
    
    def sample_across_versions(
        self,
        version_ids: List[int],
        batch_size: int,
        rng: random.Random,
        device: torch.device,
        weights: Optional[List[float]] = None,
    ) -> Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor]]:
        """
        Sample problems from multiple versions' caches.
        
        Args:
            version_ids: List of version IDs to sample from
            batch_size: Total number of problems to sample
            rng: Random number generator
            device: Target device
            weights: Optional weights for each version (default: uniform)
        
        Returns:
            Stacked tensors or None if no cache available
        """
        # Filter to versions that have caches
        available = [v for v in version_ids if v in self._version_caches 
                    and self._version_caches[v].size() > 0]
        
        if not available:
            return None
        
        # Calculate samples per version
        if weights is None:
            weights = [1.0 / len(available)] * len(available)
        else:
            # Normalize and filter to available versions
            available_weights = []
            for v in available:
                idx = version_ids.index(v)
                available_weights.append(weights[idx] if idx < len(weights) else 0)
            total = sum(available_weights)
            weights = [w / total for w in available_weights] if total > 0 else [1.0 / len(available)] * len(available)
        
        # Allocate samples per version
        samples_per_version = []
        remaining = batch_size
        for i, w in enumerate(weights[:-1]):
            n = int(batch_size * w)
            samples_per_version.append(n)
            remaining -= n
        samples_per_version.append(remaining)  # Last version gets remainder
        
        # Collect problems
        all_depot = []
        all_node_xy = []
        all_demand = []
        
        for version_id, n_samples in zip(available, samples_per_version):
            if n_samples == 0:
                continue
            result = self._version_caches[version_id].sample_batch(n_samples, rng, device)
            if result:
                depot, node_xy, demand = result
                all_depot.append(depot)
                all_node_xy.append(node_xy)
                all_demand.append(demand)
        
        if not all_depot:
            return None
        
        return (
            torch.cat(all_depot, dim=0),
            torch.cat(all_node_xy, dim=0),
            torch.cat(all_demand, dim=0),
        )
    
    def get_cache_stats(self) -> Dict[str, Any]:
        """Get statistics about all caches."""
        stats = {
            "num_versions": len(self._version_caches),
            "total_problems": sum(c.size() for c in self._version_caches.values()),
            "versions": {},
        }
        for vid, cache in self._version_caches.items():
            stats["versions"][vid] = {
                "size": cache.size(),
                "is_full": cache.is_full(),
            }
        return stats
    
    def save_all(self):
        """Save all caches to disk."""
        for cache in self._version_caches.values():
            cache.save_to_disk()
    
    def clear_version(self, version_id: int):
        """Clear cache for a specific version."""
        if version_id in self._version_caches:
            del self._version_caches[version_id]
            # Also remove disk cache
            cache_path = os.path.join(self.cache_dir, f"problems_v{version_id}.pt")
            if os.path.exists(cache_path):
                os.remove(cache_path)
