#!/bin/bash
# =============================================================================
# Diffusion Generator Distribution Visualization Script
# Usage: bash scripts/show_diffusion.sh
#
# This script visualizes the spatial distribution of demands generated by
# a trained diffusion model. It supports three modes:
#   1. Single distribution heatmap (default)
#   2. Episode structure analysis (--episode)
#   3. Distribution comparison (--compare)
# =============================================================================

set -e

# Activate conda environment
source ~/miniconda3/etc/profile.d/conda.sh
conda activate drl

# Go to project root
cd "$(dirname "$0")/.."
echo "Working directory: $(pwd)"

# =============================================================================
# CONFIGURATION - Edit these variables to change settings
# =============================================================================

# --- Checkpoint Path ---
# Path to the trained diffusion model checkpoint
CHECKPOINT="checkpoints/cotrain/static_20251203_182634/generator_cycle_1.pth"

# --- Visualization Mode ---
# Options: "heatmap", "episode", "compare"
#   - heatmap: Show spatial distribution heatmap for one distribution type
#   - episode: Detailed analysis of a single generated episode
#   - compare: Compare multiple distribution types side by side
MODE="heatmap"

# --- Distribution Type (for heatmap mode) ---
# Options: "uniform", "gaussian", "cluster"
DISTRIBUTION="uniform"

# --- Sampling Settings ---
NUM_SAMPLES=50           # Number of sampling iterations (more = smoother heatmap)
NUM_DEMANDS=30            # Number of demands per sample
GRID_SIZE=30              # Heatmap resolution (higher = more detailed)
MAP_SIZE=30               # Map size (should match training config)

# --- Output ---
SAVE_PATH="outputs/heatmap1.png"              # Leave empty to not save, or set path like "outputs/diffusion_viz.png"
NO_SHOW=""                # Set to "--no_show" to skip displaying (useful for remote servers)

# =============================================================================
# END OF CONFIGURATION
# =============================================================================

echo "=============================================="
echo "Diffusion Generator Visualization"
echo "=============================================="
echo ""
echo "Checkpoint:     ${CHECKPOINT}"
echo "Mode:           ${MODE}"
echo "Distribution:   ${DISTRIBUTION}"
echo "Samples:        ${NUM_SAMPLES}"
echo "Demands/sample: ${NUM_DEMANDS}"
echo "Grid size:      ${GRID_SIZE}"
echo "Map size:       ${MAP_SIZE}x${MAP_SIZE}"
if [[ -n "${SAVE_PATH}" ]]; then
    echo "Save path:      ${SAVE_PATH}"
fi
echo "=============================================="
echo ""

# Check if checkpoint exists
if [[ ! -f "${CHECKPOINT}" ]]; then
    echo "Error: Checkpoint not found at ${CHECKPOINT}"
    echo "Please update the CHECKPOINT variable in this script."
    exit 1
fi

# Build command based on mode
CMD=(
    python3 utils/visualize_diffusion.py
    --checkpoint "${CHECKPOINT}"
    --distribution "${DISTRIBUTION}"
    --num_samples "${NUM_SAMPLES}"
    --num_demands "${NUM_DEMANDS}"
    --grid_size "${GRID_SIZE}"
    --map_size "${MAP_SIZE}"
)

# Add mode-specific flags
case "${MODE}" in
    "episode")
        CMD+=(--episode)
        echo "Running: Episode Structure Analysis"
        ;;
    "compare")
        CMD+=(--compare)
        echo "Running: Distribution Comparison"
        ;;
    "heatmap"|*)
        echo "Running: Spatial Distribution Heatmap"
        ;;
esac

# Add optional flags
if [[ -n "${SAVE_PATH}" ]]; then
    CMD+=(--save_path "${SAVE_PATH}")
fi

if [[ -n "${NO_SHOW}" ]]; then
    CMD+=(--no_show)
fi

# =============================================================================
# Run Visualization
# =============================================================================

echo ""
echo "Executing: ${CMD[*]}"
echo ""

"${CMD[@]}"

echo ""
echo "=============================================="
echo "Visualization complete!"
if [[ -n "${SAVE_PATH}" ]]; then
    echo "Figure saved to: ${SAVE_PATH}"
fi
echo "=============================================="
