#!/usr/bin/env bash

# =============================================================================
# Visualize Diffusion V2 Generator Output
# Usage: bash scripts/visualize_diffusion_v2.sh [checkpoint_path]
#
# This script visualizes the VRP instances generated by the Diffusion V2 model.
# =============================================================================

set -euo pipefail
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR/.."

# =============================================================================
# Read configuration from static_config.py
# =============================================================================
get_config() {
    python3 -c "from static_config import $1; print($1)" 2>/dev/null || echo ""
}

# --- Default Settings ---
CHECKPOINT=${1:-$(get_config "DIFFUSION_V2_VIZ_CHECKPOINT")}

NUM_SAMPLES=$(get_config "DIFFUSION_V2_VIZ_SAMPLES")

NUM_NODES=$(get_config "NUM_NODES")

MAP_SIZE=$(get_config "MAP_SIZE")

TOTAL_DEMAND=$(get_config "TOTAL_DEMAND")

MAX_C=$(get_config "MAX_C")

CAPACITY=$(get_config "CAPACITY")

DEPOT_X=$(get_config "DIFFUSION_V2_DEPOT_X")
DEPOT_Y=$(get_config "DIFFUSION_V2_DEPOT_Y")

DDIM_STEPS=$(get_config "DIFFUSION_V2_DDIM_STEPS")

SAVE_PATH=$(get_config "DIFFUSION_V2_VIZ_SAVE_PATH")

DEVICE=$(get_config "DEVICE")

# =============================================================================
# Display Configuration
# =============================================================================

echo "=========================================="
echo "Diffusion V2 Visualization"
echo "=========================================="
echo ""
if [[ -n "$CHECKPOINT" ]]; then
    echo "  Checkpoint:     $CHECKPOINT"
else
    echo "  Checkpoint:     (random model)"
fi
echo "  Num samples:    $NUM_SAMPLES"
echo "  Num nodes:      $NUM_NODES"
echo "  Map size:       ${MAP_SIZE}x${MAP_SIZE}"
echo "  Total demand:   $TOTAL_DEMAND"
echo "  Max C:          $MAX_C"
echo "  Capacity:       $CAPACITY"
echo "  Depot:          ($DEPOT_X, $DEPOT_Y)"
echo "  DDIM steps:     $DDIM_STEPS"
echo "  Save path:      $SAVE_PATH"
echo "  Device:         $DEVICE"
echo ""
echo "=========================================="
echo ""

# Create output directory
mkdir -p "$(dirname "$SAVE_PATH")"

# =============================================================================
# Build Command
# =============================================================================

cmd=(
    python3 -m diffusion_v2.visualize
    --num-samples "$NUM_SAMPLES"
    --num-nodes "$NUM_NODES"
    --map-size "$MAP_SIZE"
    --total-demand "$TOTAL_DEMAND"
    --max-c "$MAX_C"
    --capacity "$CAPACITY"
    --depot-x "$DEPOT_X"
    --depot-y "$DEPOT_Y"
    --ddim-steps "$DDIM_STEPS"
    --save-path "$SAVE_PATH"
    --device "$DEVICE"
)

if [[ -n "$CHECKPOINT" ]]; then
    cmd+=(--checkpoint "$CHECKPOINT")
fi

"${cmd[@]}"

echo ""
echo "Visualization saved to: $SAVE_PATH"
